repos:
 - repo: https://github.com/pre-commit/mirrors-autopep8
   rev: v1.4.4 # Use the sha / tag you want to point at
   hooks:
    - id: autopep8
      args: [-i]
 - repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v2.4.0
   hooks:
    - id: flake8
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
